App\Entity\Projet\Projet\Traceconnexion:
    collectionOperations:
        projet_projet_traceconnexions_client_id:
            method: GET
            path: '/traceconnexions/identify'
            controller: App\Controller\Projet\Projet\TraceconnexionController::traceconnexionClientId
            openapi_context:
                summary: Endpoint pour filtrer un projet en fonction du client
                description: Ressources liées aux projets
                parameters:
                  - in: query
                    name: clientId
                    schema:
                        type: string
                        default: ''
                    required: true
                    description: Indiquez l'Id du client
        projet_projet_traceconnexion_fetch_user:
            method: POST
            path: '/traceconnexion/generate/accesstoken'
            controller: App\Controller\Projet\Projet\TraceconnexionController::generateaccesstoken
            openapi_context:
                summary: Endpoint pour créer une annonce
                description: Ressource de création
                requestBody:
                    description: Données *Json* à fournir
                    required: true
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    clientSecret:
                                        type: string
                                    authcode:
                                        type: string
        projet_projet_liste_traceconnexion:
            method: GET
            path: '/traceconnexions/connect/{position}'
            controller: App\Controller\Projet\Projet\TraceconnexionController::listeTraceconnexion
            openapi_context:
                summary: Endpoint pour faire la recherche sur les articles (back-office)
                description: Ressources liées aux articles
                parameters:
                  - in: query
                    name: page
                    schema:
                        type: integer
                        minimum: 1
                        default: 1
                    required: true
                    description: Indiquez le Numéro de page
                  - in: query
                    name: tail
                    schema:
                        type: integer
                        default: 10
                    required: true
                  - in: path
                    name: position
                    schema:
                        type: string
                        default: dashboard
                    required: false
                    description: Indiquer la position

    itemOperations:
        get: ~
        projet_projet_update_traceconnexion:
            method: PUT
            path: '/traceconnexions/{id}'
            controller: App\Controller\Projet\Projet\TraceconnexionController::updateTraceconnexion
            openapi_context:
                summary: Endpoint pour mettre à jour une trace
                description: Ressource de connexion
                parameters:
                  - in: path
                    name: id
                    schema:
                        type: integer
                        minimum: 1
                    required: true
                    description: Indiquer l'id de l'annonce
                requestBody:
                    description: Renseigner les données à modifier
                    required: true
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    iduser:
                                        type: integer