#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
    path: /api/login
    methods: ['POST']
app_directory_afhaccount:
    resource: '../src/Routing/Projet/'
    type: directory
